# Generated by Django 5.2 on 2026-03-24 12:41

import datetime
import django.db.models.deletion
import fin.models.utils
import fin.schemas.xbrl
import pathlib
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("title", models.CharField(default="", max_length=256, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Book template",
                "verbose_name_plural": "Book templates",
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("title", models.CharField(default="", max_length=256, verbose_name="Title")),
                (
                    "xbrl",
                    fin.models.utils.PydanticJSONField(
                        blank=True, null=True, schema=fin.schemas.xbrl.XBRLSchema, verbose_name="XBRL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("title", models.CharField(default="", max_length=256, verbose_name="Title")),
                (
                    "path",
                    models.FilePathField(
                        allow_files=False,
                        allow_folders=True,
                        blank=True,
                        path=pathlib.PurePosixPath("/home/data/code/projets/ox-fin/media/books"),
                        unique=True,
                        verbose_name="Document directory",
                    ),
                ),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ox_fin.booktemplate")),
            ],
            options={
                "verbose_name": "Ledger Book",
                "verbose_name_plural": "Ledger books",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("code", models.CharField(blank=True, max_length=10, null=True, verbose_name="Code")),
                ("short", models.CharField(blank=True, max_length=10, null=True, verbose_name="Abbreviation")),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Other (General ledger account)"),
                            (1, "View (Non-postable group)"),
                            (2, "Depreciation"),
                            (3, "Tax (VAT, Corporate, etc.)"),
                            (4, "Off Balance Sheet"),
                            (16, "Assets"),
                            (17, "Expense"),
                            (18, "Receivable (Customer)"),
                            (19, "Liquidity (Cash/Bank)"),
                            (20, "Stock Inventory"),
                            (32, "Liability"),
                            (33, "Equity"),
                            (34, "Revenue"),
                            (35, "Payable (Vendor)"),
                        ],
                        default=0,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_debit",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(then=models.Value(True), type__in=[16, 17, 18, 19, 20]),
                            models.When(then=models.Value(False), type__in=[32, 33, 34, 35]),
                            default=models.Value(None),
                        ),
                        output_field=models.BooleanField(null=True),
                        verbose_name="Is debit",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="accounts", to="ox_fin.booktemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "code",
                    models.CharField(help_text='For example "FIN" for "Finance".', max_length=10, verbose_name="Code"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="journals", to="ox_fin.booktemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document", models.FileField(blank=True, null=True, upload_to="", verbose_name="Document")),
                ("date", models.DateField(default=datetime.date.today, verbose_name="Date")),
                ("reference", models.CharField(blank=True, max_length=64, null=True, verbose_name="Reference")),
                ("description", models.CharField(max_length=128, verbose_name="Description")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="moves", to="ox_fin.book"
                    ),
                ),
                ("journal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ox_fin.journal")),
            ],
            options={
                "verbose_name": "Move",
                "verbose_name_plural": "Moves",
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amount")),
                ("is_debit", models.BooleanField(verbose_name="Is Debit")),
                (
                    "is_credit",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(is_debit=False, then=models.Value(True)),
                            default=models.Value(False),
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                        verbose_name="Is Credit",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ox_fin.account", verbose_name="Account"
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="ox_fin.move"
                    ),
                ),
            ],
            options={
                "verbose_name": "Line",
                "verbose_name_plural": "Lines",
            },
        ),
        migrations.CreateModel(
            name="MoveRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("code", models.CharField(max_length=32, verbose_name="Code")),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="move_rules", to="ox_fin.journal"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="move_rules", to="ox_fin.booktemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Move ruleset",
                "verbose_name_plural": "Move rulesets",
            },
        ),
        migrations.CreateModel(
            name="LineRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Order")),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Python expression that is used to compute value when it is not provided. Input values includes thoses of other rules of the ruleset",
                        max_length=100,
                        verbose_name="Formula",
                    ),
                ),
                (
                    "is_debit",
                    models.BooleanField(
                        blank=True,
                        help_text="If True or False, ensure the value is set to debit/credit column.",
                        null=True,
                        verbose_name="Is debit",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="ox_fin.account"
                    ),
                ),
                (
                    "move_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="line_rules", to="ox_fin.moverule"
                    ),
                ),
            ],
            options={
                "verbose_name": "Line Rule",
                "verbose_name_plural": "Line Rules",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ox_fin.book", verbose_name="Ledger Book"
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ox_fin.report",
                        verbose_name="Previous Report",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ox_fin.reporttemplate", verbose_name="Template"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportSectionTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                ("code", models.CharField(blank=True, max_length=16, null=True, verbose_name="Code")),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=Decimal("1"), max_digits=3, verbose_name="Weight"),
                ),
                ("formula", models.CharField(blank=True, max_length=128, null=True, verbose_name="Formula")),
                ("annexe", models.CharField(blank=True, max_length=16, null=True, verbose_name="Annexe")),
                (
                    "xbrl",
                    fin.models.utils.PydanticJSONField(
                        blank=True, null=True, schema=fin.schemas.xbrl.XBRLFact, verbose_name="XBRL"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ox_fin.reportsectiontemplate",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        help_text="Get value from the section of the previous report.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ox_fin.reportsectiontemplate",
                        verbose_name="Previous Section",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="ox_fin.reporttemplate",
                        verbose_name="Report Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Section",
                "verbose_name_plural": "Report Sections",
            },
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                ("code", models.CharField(blank=True, max_length=16, null=True, verbose_name="Code")),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=Decimal("1"), max_digits=3, verbose_name="Weight"),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Value")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ox_fin.reportsection",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="ox_fin.report",
                        verbose_name="Report",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ox_fin.reportsectiontemplate",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
