# Generated by Django 5.2 on 2025-04-24 16:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
            ],
            options={
                "verbose_name": "Book template",
                "verbose_name_plural": "Book templates",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("path", models.FilePathField(unique=True, verbose_name="Document directory")),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ox_fin.booktemplate")),
            ],
            options={
                "verbose_name": "Ledger Book",
                "verbose_name_plural": "Ledger books",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("code", models.CharField(blank=True, max_length=10, null=True, verbose_name="Code")),
                ("short", models.CharField(blank=True, max_length=10, null=True, verbose_name="Abbreviation")),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Other (General ledger account)"),
                            (1, "View (Non-postable group)"),
                            (2, "Depreciation"),
                            (3, "Tax (VAT, Corporate, etc.)"),
                            (4, "Off Balance Sheet"),
                            (16, "Assets"),
                            (17, "Expense"),
                            (18, "Receivable (Customer)"),
                            (19, "Liquidity (Cash/Bank)"),
                            (20, "Stock Inventory"),
                            (32, "Liability"),
                            (33, "Equity"),
                            (34, "Revenue"),
                            (35, "Payable (Vendor)"),
                        ],
                        default=0,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_debit",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(then=models.Value(True), type__in=[16, 17, 18, 19, 20]),
                            models.When(then=models.Value(False), type__in=[32, 33, 34, 35]),
                            default=models.Value(None),
                        ),
                        output_field=models.BooleanField(null=True),
                        verbose_name="Is debit",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="accounts", to="ox_fin.booktemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "code",
                    models.CharField(help_text='For example "FIN" for "Finance".', max_length=10, verbose_name="Code"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="journals", to="ox_fin.booktemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document", models.FileField(blank=True, null=True, upload_to="", verbose_name="Document")),
                ("date", models.DateField(default=datetime.date.today, verbose_name="Date")),
                ("reference", models.CharField(blank=True, max_length=64, null=True, verbose_name="Reference")),
                ("label", models.CharField(max_length=128, verbose_name="Label")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="moves", to="ox_fin.book"
                    ),
                ),
                ("journal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ox_fin.journal")),
            ],
            options={
                "verbose_name": "Move",
                "verbose_name_plural": "Moves",
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amount")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ox_fin.account", verbose_name="Account"
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="ox_fin.move"
                    ),
                ),
            ],
            options={
                "verbose_name": "Move line",
                "verbose_name_plural": "Move lines",
            },
        ),
        migrations.CreateModel(
            name="MoveRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("code", models.CharField(max_length=32, verbose_name="Code")),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="move_rules", to="ox_fin.journal"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="move_rules", to="ox_fin.booktemplate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Move Rule",
                "verbose_name_plural": "Move Rules",
            },
        ),
        migrations.CreateModel(
            name="LineRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("code", models.CharField(blank=True, max_length=10, null=True, verbose_name="Code")),
                ("order", models.PositiveSmallIntegerField(default=100, verbose_name="Order")),
                ("formula", models.CharField(blank=True, max_length=100, default="", verbose_name="Formula")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="ox_fin.account"
                    ),
                ),
                (
                    "move_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="line_rules", to="ox_fin.moverule"
                    ),
                ),
            ],
            options={
                "verbose_name": "Line Rule",
                "verbose_name_plural": "Line Rules",
            },
        ),
    ]
