# Generated by Django 5.2 on 2026-02-19 15:39

import django.db.models.deletion
import pathlib
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_fin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("label", models.CharField(max_length=64, verbose_name="Label")),
            ],
            options={
                "verbose_name": "Report Template",
                "verbose_name_plural": "Report Templates",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="path",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                blank=True,
                path=pathlib.PurePosixPath("/home/data/code/projets/ox-fin/media/books"),
                unique=True,
                verbose_name="Document directory",
            ),
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                ("label", models.CharField(max_length=256, verbose_name="Label")),
                ("code", models.CharField(blank=True, max_length=16, null=True, verbose_name="Code")),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=Decimal("1"), max_digits=3, verbose_name="Weight"),
                ),
                ("formula", models.CharField(max_length=128, verbose_name="Formula")),
                ("annexe", models.CharField(blank=True, max_length=16, null=True, verbose_name="Annex")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ox_fin.reportsection",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="ox_fin.reporttemplate",
                        verbose_name="Report Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Section",
                "verbose_name_plural": "Report Sections",
            },
        ),
    ]
