# Generated by Django 5.2 on 2025-04-25 08:42

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_fin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="line",
            options={"verbose_name": "Line", "verbose_name_plural": "Lines"},
        ),
        migrations.AlterModelOptions(
            name="moverule",
            options={"verbose_name": "Move ruleset", "verbose_name_plural": "Move rulesets"},
        ),
        migrations.AddField(
            model_name="linerule",
            name="is_debit",
            field=models.BooleanField(
                blank=True,
                help_text="If True or False, ensure the value is set to debit/credit column.",
                null=True,
                verbose_name="Is debit",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="path",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                blank=True,
                path=pathlib.PurePosixPath("/media/data/code/projets/ox-fin/media/books"),
                unique=True,
                verbose_name="Document directory",
            ),
        ),
        migrations.AlterField(
            model_name="linerule",
            name="code",
            field=models.CharField(default="", max_length=10, verbose_name="Code"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="linerule",
            name="formula",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Python expression that is used to compute value when it is not provided. Input values includes thoses of other rules of the ruleset",
                max_length=100,
                verbose_name="Formula",
            ),
        ),
    ]
