# Generated by Django 5.2 on 2026-03-31 14:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_fin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmortizationSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "start_date",
                    models.DateField(
                        help_text="Start of the amortization (usually acquisition date or first use).",
                        verbose_name="Start Date",
                    ),
                ),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "method",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Linear"), (1, "Degressive")], default=0, verbose_name="Method"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Monthly"), (3, "Quarterly"), (12, "Annual")], default=12, verbose_name="Frequency"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name="Rate"),
                ),
                (
                    "prorata",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(0, "None"), (1, "Daily"), (2, "Full month")],
                        help_text="Override ledger book's prorata policy of amortization.",
                        null=True,
                        verbose_name="Prorata Policy",
                    ),
                ),
                (
                    "residual_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Expected asset value after amortization has been fully applied.",
                        max_digits=12,
                        verbose_name="Residual Value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amortization",
                "verbose_name_plural": "Amortizations",
            },
        ),
        migrations.AlterModelOptions(
            name="line",
            options={"verbose_name": "Journal Entry Line", "verbose_name_plural": "Journal Entry Lines"},
        ),
        migrations.AlterModelOptions(
            name="move",
            options={"verbose_name": "Journal Entry", "verbose_name_plural": "Journal Entries"},
        ),
        migrations.RemoveField(
            model_name="book",
            name="name",
        ),
        migrations.AddField(
            model_name="book",
            name="amortization_prorata",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "None"), (1, "Daily"), (2, "Full month")],
                default=0,
                verbose_name="Amortizations Prorata Policy",
            ),
        ),
        migrations.CreateModel(
            name="AmortizationEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amount")),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        help_text="The journal entry applying the amortization.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amortization_entries",
                        to="ox_fin.move",
                        verbose_name="Journal Entry",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ox_fin.amortizationschedule",
                        verbose_name="Amortization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amortization Entry",
                "verbose_name_plural": "Amortization Entries",
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("reference", models.CharField(blank=True, max_length=64, null=True, verbose_name="Reference")),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Intangible Asset"), (1, "Tangible Asset"), (2, "Financial Asset")],
                        verbose_name="Type",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Initial Value")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="fixed_assets", to="ox_fin.book"
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        help_text="The journal entry of the asset's acquisition.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ox_fin.move",
                        verbose_name="Journal Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Asset",
                "verbose_name_plural": "Fixed Assets",
            },
        ),
        migrations.AddField(
            model_name="amortizationschedule",
            name="asset",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amortization_schedule",
                to="ox_fin.fixedasset",
            ),
        ),
    ]
