# Generated by Django 5.2 on 2026-03-31 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_fin", "0002_amortizationschedule_alter_line_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amortizationschedule",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="amortizations", to="ox_fin.fixedasset"
            ),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="description",
            field=models.CharField(max_length=128, verbose_name="Description"),
        ),
    ]
