# Generated by Django 5.2 on 2026-03-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_fin", "0003_report_reportsectionresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportsection",
            name="label",
        ),
        migrations.RemoveField(
            model_name="reporttemplate",
            name="label",
        ),
        migrations.AddField(
            model_name="book",
            name="label",
            field=models.CharField(default="", max_length=128, verbose_name="Label"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booktemplate",
            name="title",
            field=models.CharField(default="", max_length=256, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="reportsection",
            name="name",
            field=models.CharField(default="", max_length=256, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="title",
            field=models.CharField(default="", max_length=256, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="formula",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Formula"),
        ),
        migrations.AlterField(
            model_name="reportsectionresult",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ox_fin.reportsection", verbose_name="Section"
            ),
        ),
    ]
