# Generated by Django 5.2 on 2026-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_fin", "0004_remove_reportsection_label_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="label",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(default="", max_length=256, verbose_name="Title"),
        ),
    ]
