# Generated by Django 5.2 on 2026-03-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ox_fin", "0005_rename_label_book_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="move",
            name="label",
        ),
        migrations.AddField(
            model_name="move",
            name="description",
            field=models.CharField(default="", max_length=128, verbose_name="Description"),
            preserve_default=False,
        ),
    ]
